apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: signing-secrets
  namespace: openshift-pipelines
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: signing-secrets
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.cosignsecret.key }}
