apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: signing-secrets
  namespace: openshift-pipelines
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: signing-secrets
    template:
      type: Opaque
      labels:
        app.kubernetes.io/component: chains
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: tekton-pipelines
        pipeline.tekton.dev/release: devel
        version: v0.8.0
      name: signing-secrets
      namespace: openshift-pipelines
  dataFrom:
  - extract:
      key: {{ .Values.cosignsecret.key }}
