apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: multiclusterhub-operator-pull-secret
    template:
      type: "kubernetes.io/dockerconfigjson"
  dataFrom:
  - extract:
      key: {{ .Values.pullSecret.key | base64encode }}