apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: thanos-object-storage
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.observabilityStorage.key }}

# Secret in vault must have S3 information under thanos.yaml key as per below
# apiVersion: v1
# kind: Secret
# metadata:
#   name: thanos-object-storage
#   namespace: open-cluster-management-observability
# type: Opaque
# stringData:
#   thanos.yaml: |
#     type: s3
#     config:
#       bucket: YOUR_S3_BUCKET
#       endpoint: YOUR_S3_ENDPOINT
#       insecure: true
#       access_key: YOUR_ACCESS_KEY
#       secret_key: YOUR_SECRET_KEY